# Generated by Django 5.0 on 2023-12-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Science fiction', 'Science fiction'), ('PSC', 'PSC'), ('Polictics', 'Polictics'), ('Finance', 'Finance'), ('Fiction', 'Fiction')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
