# Generated by Django 5.0 on 2024-01-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_alter_book_category_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
