# Generated by Django 5.0 on 2024-01-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_book_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='search',
        ),
    ]
